services:
  db:
    image: mysql:8.0
    container_name: moodle-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=moodle_root_pass_2026
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodleuser
      - MYSQL_PASSWORD=moodlepass123
    volumes:
      - moodle-db-data:/var/lib/mysql

  moodle:
    image: jhardison/moodle:latest
    container_name: moodle-app
    depends_on:
      - db
    restart: always
    ports:
      - "8081:80"
    environment:
      - MOODLE_URL=http://localhost:8081
      - DB_PORT_3306_TCP_ADDR=db
      - DB_PORT_3306_TCP_PORT=3306
      - DB_ENV_MYSQL_DATABASE=moodle
      - DB_ENV_MYSQL_USER=moodleuser
      - DB_ENV_MYSQL_PASSWORD=moodlepass123
    volumes:
      - moodle-data:/var/www/html
      - moodledata:/var/moodledata

volumes:
  moodle-data:
    external: true
    name: moodle-setup_moodle-data
  moodledata:
    external: true
    name: moodle-setup_moodledata
  moodle-db-data:
    external: true
    name: moodle-setup_moodle-db-data
